export const WS_API = {
  LOGIN: 'LOGIN',
  CLIENT_SEND_CHAT: 'CLIENT_SEND_CHAT',
  SERVER_SEND_CHAT: 'SERVER_SEND_CHAT',
  LOAD_CHAT: 'LOAD_CHAT',
  JOIN_CHANNELS: 'JOIN_CHANNELS',
  GET_CONTACTS: 'GET_CONTACTS',
  GET_USER: 'GET_USER'
};